#!/usr/bin/env python3
"""Generate a C++ header with SHA-256 hashes of critical Python source files.

Run before compiling native modules. The generated header is included
by rig2_face_cap.cpp and rig2_miframes.cpp so the integrity hashes
are always current with the actual Python source.
"""

import hashlib
import os
import sys
from pathlib import Path

# Files to hash, given relative to the repo root.
WATCH_FILES = [
    "src/services/face_cap_service.py",
    "src/services/miframes_service.py",
    "src/licensing/manager.py",
]

HEADER_GUARD = "RIG2_NATIVE_INTEGRITY_HASHES_H"


def compute_hash(filepath: Path) -> str:
    """Return the hex SHA-256 digest of a file."""
    h = hashlib.sha256()
    with open(filepath, "rb") as fh:
        while True:
            chunk = fh.read(65536)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def generate_header(repo_root: Path, output_path: Path) -> None:
    """Write the hashes header file."""
    lines = [
        "// Auto-generated by scripts/generate_integrity_hashes.py",
        "// Do not edit manually.",
        f"#ifndef {HEADER_GUARD}",
        f"#define {HEADER_GUARD}",
        "",
        "// Expected SHA-256 hashes of critical Python source files.",
        "// Each entry: {filename, expected_hex_hash}",
        "static const char* kExpectedPyHashes[] = {",
    ]

    for rel_path in WATCH_FILES:
        filepath = repo_root / rel_path
        if not filepath.exists():
            print(f"WARNING: {rel_path} not found, using empty hash", file=sys.stderr)
            hex_hash = ""
        else:
            hex_hash = compute_hash(filepath)
            print(f"  {rel_path}: {hex_hash}")

        # Extract just the filename for the C++ table key.
        fname = os.path.basename(rel_path)
        lines.append(f'    "{fname}", "{hex_hash}",')

    lines.extend([
        "    nullptr,",
        "};",
        "",
        f"#endif  // {HEADER_GUARD}",
        "",
    ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated: {output_path}")


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    output_path = repo_root / "native_cpp" / "src" / "integrity_hashes.h"
    generate_header(repo_root, output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
