#!/usr/bin/env python3
"""Generate a C++ header with SHA-256 hashes of critical Python source files.

Run before compiling native modules. The generated header is included
by rig2_face_cap.cpp and rig2_miframes.cpp so the integrity hashes
are always current with the actual Python source.
"""

import hashlib
import importlib.util
import sys
from pathlib import Path

HEADER_GUARD = "RIG2_NATIVE_INTEGRITY_HASHES_H"


def load_registry(repo_root: Path):
    registry_path = repo_root / "src" / "licensing" / "registry.py"
    spec = importlib.util.spec_from_file_location("rig2_generate_integrity_registry", registry_path)
    module = importlib.util.module_from_spec(spec)
    assert spec is not None and spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def compute_hash(filepath: Path) -> str:
    """Return the hex SHA-256 digest of a file."""
    h = hashlib.sha256()
    with open(filepath, "rb") as fh:
        while True:
            chunk = fh.read(65536)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def generate_header(repo_root: Path, output_path: Path) -> None:
    """Write the hashes header file."""
    registry = load_registry(repo_root)
    lines = [
        "// Auto-generated by scripts/generate_integrity_hashes.py",
        "// Do not edit manually.",
        f"#ifndef {HEADER_GUARD}",
        f"#define {HEADER_GUARD}",
        "",
        "// Expected SHA-256 hashes of critical Python source files.",
        "// Each entry: {filename, expected_hex_hash}",
    ]

    for spec in registry.iter_native_feature_specs():
        array_name = f'kExpectedPyHashes_{spec.native_module_name}'
        lines.append("")
        lines.append(f"static const char* {array_name}[] = {{")
        for fname, relative_path in spec.integrity_targets:
            filepath = repo_root / "src" / relative_path
            if not filepath.exists():
                print(f"WARNING: {relative_path} not found, using empty hash", file=sys.stderr)
                hex_hash = ""
            else:
                hex_hash = compute_hash(filepath)
                print(f"  {spec.native_module_name}:{relative_path}: {hex_hash}")
            lines.append(f'    "{fname}", "{hex_hash}",')
        lines.append("    nullptr,")
        lines.append("};")

    lines.extend([ "", f"#endif  // {HEADER_GUARD}", "" ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated: {output_path}")


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    output_path = repo_root / "native_cpp" / "src" / "integrity_hashes.h"
    generate_header(repo_root, output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
